### ISSUE TITLE
上传时最后一片总失败

### ISSUE THREAD

**Issue by kingkadienm** [shilec/Transer#1]
Session-ID: d883d660-8acf-4c25-b3f3-9d8f4019edfc
 X-Content-Range: bytes 37748736-38797311/38945179
Content-Disposition: attachment;name="file";filename="test.apk"
Connection: Keep-Alive

这是最后一片上传的header

**Comment by shilec** [comment]
这个看起来不应该是最后一片，服务端是通过Content-Range 获取 当前上传的起始偏移量和长度，正常情况下最后一片start-end/all 应该为 end = all - 1. 你demo试试是否可以 SimpleUploadActivity

**Comment by kingkadienm** [comment]
嗯，这个已解决，是我seek的时候把暂停的位置记错了，导致从新长传，还有一个问题，我用你写的下载的时候，下载的每一片的进度都不会显示只有在你下载成功的时候才会有进度显示成功，用我自己写的就没问题，能指导一下吗？

**Comment by kingkadienm** [comment]
我就是直接把URL替换的，发现不行

**Comment by shilec** [comment]
麻烦把url发一下，我试试

**Comment by kingkadienm** [comment]
我这边URL是有认证信息的，能不能加下QQ或者别的发你？

**Comment by shilec** [comment]
好的，发我邮箱吧，shilec@126.com
