### ISSUE TITLE
关于分片上传的进度问题?

### ISSUE THREAD

**Issue by Chenshuai770** [shilec/Transer#2]
大神,你好,我想问下在你的SimpleUploadActivity里面SimpleTaskHandlerListenner中有三个方法,onPiceSuccessful.onFinished,onSpeedChanged中,哪个是最后一个,就是当我上传成功后会具体执行到哪个方法里面,我debug出来,有的时候回到onSpeedChanged,有的时候回到onPiceSuccessful,但是不会到onFinished方法里面去

**Comment by Chenshuai770** [comment]
我需要监听到的上传成功之后跳转页面

**Comment by Chenshuai770** [comment]
还有大神,有时候就会卡在最后一点点,比如进度条到98%或者99%的时候就卡住了,调到onError里面去了,这个是网络的问题吗

**Comment by shilec** [comment]
1. 最后一片上传完毕后，会回调onFinished或者onError, 判断条件取决于 DefalutUploadHanlder 中的 isSuccessful() 的返回值，所以需要去修改isSuccessful 或 继承 DefaultUploadHandler 重写 isSuccessful()方法。例如:最后一片上传完毕，需要在isSuccessful中校验服务器的返回值

**Comment by shilec** [comment]
onSpeedChanged:是在一个单独的线程中去执行的，为了不阻塞传输线程，限制传输速度。所以会出现onLengthChanged和onSpeedChanged 顺序随机出现的问题。

**Comment by shilec** [comment]
还有大神,有时候就会卡在最后一点点,比如进度条到98%或者99%的时候就卡住了,调到onError里面去了,这个是网络的问题吗

onError 出现的情况:
1.网络出现错误。
2.在一片上传完成后，会判断isPiceSuccessful()，去校验服务器在客户端上传完成一片后的返回值，你需要修改或重写 isPiceSuccessful()

**Comment by Chenshuai770** [comment]
大神,怎么修改最后一片的isSuccessful()的代码,服务端的代码不是我写的,我之前调用的进度99%的时候基本会调用到onError,然后卡着不动,而且每次调用成功后我不会执行到onFinished,是不是isSuccessful为ture的时候就能执行到了

**Comment by Chenshuai770** [comment]
mHandler.setHeaders("");这个方法用来指定到cookies的时候并没有效果,需要到DefaultHttpUploadHandler中的Request指定头文件才行

**Comment by shilec** [comment]
1.例如:上传成功的返回值为 {code:0}
修改DefaultUploadHandler 中的isSuccessful()

try {
    JSONOjbect jobj = new JSONobject(mResonse);
int code = jobj.opt("code");
if(code == 0) return true;
} catch(Exeception e) {
}
return false;

**Comment by shilec** [comment]
抱歉，setHeaders这个方法没有实现。之后版本会修改

**Comment by shilec** [comment]
客气了， 如果发现什么问题请提出来，多谢。
