### ISSUE TITLE
怎么设置才能让@TaskSubscriber 接收上传的而不是数据库所有的，TaskCmd里设置了我想要的taskid，和state 但是从@TaskSubscriber数据回来的时候还是数据库全部数据，这样不是变相的占用了资源？

### ISSUE THREAD

**Issue by kingkadienm** [shilec/Transer#4]

**Comment by shilec** [comment]
@TaskSubscriber(taskType=TaskType.HTTP_UPLOAD,processType=ProcessType.ADD_TASK,threadMode=ThreadMode.MODE_MAIN)

taskType 过滤上传任务 还是下载任务

**Comment by kingkadienm** [comment]
过滤的上传，这个是我的cmd，接收到的是数据库的全部上传任务，我想只接收正在上传的
            String[] taskID = intent.getStringArrayExtra(TASKID_LIST);
            TaskCmd cmd = new TaskCmd.Builder()
                    .setUserId(AppMgr.getUserId())
                    .setTaskType(TaskType.TYPE_HTTP_UPLOAD)
                    .setTaskIds(taskID)
                    .setProcessType(ProcessType.TYPE_START_TASK)
                    .build();
            TaskEventBus.getDefault().execute(cmd);

**Comment by kingkadienm** [comment]
还有一种情况不知道您遇没遇到，就是我点击跳转到选择本地文件的界面，然后什么操作都不进行，返回到上传列表，这时候会接收到重复的数据，我跳转几次就会有重复几次，在数据回来的时候我会把list给clean了，然后在add数据，还是出现重复的
这是我接收的
@TaskSubscriber(taskType = TaskType.TYPE_HTTP_UPLOAD,
            processType = {
                    ProcessType.TYPE_UPDATE_TASK,
                    ProcessType.TYPE_DELETE_TASK,
                    ProcessType.TYPE_ADD_TASKS,
                    ProcessType.TYPE_QUERY_TASKS_STATE,
                    ProcessType.TYPE_QUERY_TASKS_GROUP
            },
            threadMode = ThreadMode.MODE_MAIN)

这个是在onResume里的cmd
   TaskEventBus.getDefault().regesit(this);
            TaskCmd cmd = new TaskCmd.Builder()
                    .setUserId(AppMgr.getUserId())
                    .setGroupId(groupId)
                    .setTaskType(TaskType.TYPE_HTTP_UPLOAD)
                    .setProcessType(ProcessType.TYPE_QUERY_TASKS_GROUP)
                    .build();
            TaskEventBus.getDefault().execute(cmd);

**Comment by kingkadienm** [comment]
这个是我第一次进去是正确的一条数据(数据库也是一条数据)，  然后跳转再返回 ，出现两条数据(这时候这两条数据是一模一样的)，然后又重复，是三条一模一样的数据，我觉得是unregesit的时候没把数据彻底清除

![Uploading image.png…]()
![Uploading Snipaste_2018-08-01_17-38-30.png…]()
![Uploading Snipaste_2018-08-01_17-38-48.png…]()

**Comment by kingkadienm** [comment]
这个是我第一次进去是正确的一条数据(数据库也是一条数据)， 然后跳转再返回 ，出现两条数据(这时候这两条数据是一模一样的)，然后又重复，是三条一模一样的数据，我觉得是unregesit的时候没把数据彻底清除
![snipaste_2018-08-01_17-38-09](https://user-images.githubusercontent.com/25675286/43514739-6a6f58d6-95b3-11e8-8a0e-72cc7f574acb.png)
![snipaste_2018-08-01_17-38-30](https://user-images.githubusercontent.com/25675286/43514740-6abc0d5c-95b3-11e8-9109-f9f52a72ecb2.png)
![snipaste_2018-08-01_17-38-48](https://user-images.githubusercontent.com/25675286/43514742-6b074934-95b3-11e8-9f15-83fbc1219aaa.png)

**Comment by shilec** [comment]
是使用的demo测试的吗？我这边使用demo测试不复现你描述的情况

**Comment by kingkadienm** [comment]
我这个是集成到项目里的，今天早上再测试的时候没有这种现象了，代码还是以前的，这个问题是偶现的，但是出现一次的话，接下来会持续出现。这个其实也不好复现，从我集成到项目中大概五个月出现了四五次左右

**Comment by shilec** [comment]
抱歉，这几天有点忙，我会尽快找到问题解决

**Comment by kingkadienm** [comment]
您好，这个问题我已经解决，但是遇到了一个新的，就是我上传一百多兆的文件的时候，读取文件的时候会内存泄露，但是我看了我读取完每一片的时候也都close。
![image](https://user-images.githubusercontent.com/25675286/44140471-becb00f2-a0ac-11e8-9353-3fd258064406.png)
![image](https://user-images.githubusercontent.com/25675286/44140589-1543f2e0-a0ad-11e8-9651-85bf4ba2a574.png)

**Comment by shilec** [comment]
内存泄漏的原因不太好定位，后续我会持续优化这块儿

**Comment by kingkadienm** [comment]
刚才试了下您写的下载，发现有一点问题，我下载完成后回调才会回来，在下载过程中是task的状态是等待中，知道下载完成后，task的状态才会发生改变，这个是因为下载过程中在别的线程中执行，然后下载完成后在返回在主线程么？
