### ISSUE TITLE
关于Multipart上传

### ISSUE THREAD

**Issue by chengxinping** [shilec/Transer#5]
请问如何设置文件Multipart上传

**Comment by shilec** [comment]
可以实现自定义的TaskHandle和TaskHandlerFactory , Multipart 上传，相当于只传输一片。将文件分片大小设置为要上传的文件大小即可。

**Comment by shilec** [comment]
需要集成自BaseTaskHandler，实现抽象方法。再实现一个HandlerFactory 继承自 AbsHandlerFactory, 最后在TranserConfig 的 中 addHandlerFactory 添加 HandlerFactory

**Comment by chengxinping** [comment]
好的 我试试  感谢您的回复
