### ISSUE TITLE
怎么通过task拿到切片后的每一片大小

### ISSUE THREAD

**Issue by chengxinping** [shilec/Transer#6]
您好，我现在需要在上传之前就拿到切片之后每一片的大小，请问能通过task拿到吗

**Comment by shilec** [comment]
分片大小其实是在TaskHandler中预定义的，也可以自定义修改。定义在BaseTaskHandler 中，默认是1MB每片，当然文件的大小不一定是1MB的整数倍，最后一片的大小是一个余数，小于等于 1MB.

**Comment by shilec** [comment]
BaseTaskHandler 的子类可以重写     protected int getPiceBuffSize() {} 去自定义分片大小
