### ISSUE TITLE
通过任务管理器添加的任务怎么在activity里面拿到服务器最后一片的结果

### ISSUE THREAD

**Issue by chengxinping** [shilec/Transer#7]
![image](https://user-images.githubusercontent.com/18040985/44520423-56a18800-a702-11e8-8d2a-5fe3618343df.png)
您好，请问在这个回调里面能拿到成功时服务器返回的数据吗

**Comment by shilec** [comment]
在Task 中是取不到的，如果想处理服务器的返回值，可以在TaskHandler 中，参考 MySaveResponseUploadHandler
